# Generated by Django 4.1.3 on 2023-09-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskapp',
            name='completedTill',
            field=models.DateTimeField(null=True),
        ),
    ]
